server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
            - "http://localhost:3000"
            - "http://74.249.43.156:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # Definicja tras (Routes)
      routes:
        # --- Trasy do USER-SERVICE ---
        - id: user-service-auth
          uri: ${USER_SERVICE_URI:http://localhost:8081} 
          predicates:
            - Path=/api/auth/**

        - id: user-service-users
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/**

        # --- Trasy do BETTING-SERVICE ---
        - id: betting-service-events
          uri: ${BETTING_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/api/v1/events/**

        - id: betting-service-bets
          uri: ${BETTING_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/api/v1/bets/**

        - id: betting-service-coupons
          uri: ${BETTING_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/api/v1/coupon/**

        - id: betting-service-admin
          uri: ${BETTING_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/api/v1/admin/**

        # --- Trasy do ODDS-GENERATOR ---
        - id: odds-generator-stats
          uri: ${ODDS_SERVICE_URI:http://localhost:8082}
          predicates:
              - Path=/api/v1/generator/stats/**
